RadarService.WebApp/Areas/Authorization/Controllers/RoleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RadarService.Authorization.Dtos;
using RadarService.Authorization.Models;
using RadarService.Authorization.Services;
using RadarService.WebApp.Areas.Authorization.Dtos;

namespace RadarService.WebApp.Areas.Authorization.Controllers
{
    [Area("Authorization")]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;

        public RoleController(IRoleService roleService, IMapper mapper)
        {

            _roleService = roleService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetList()
        {
            return Json(_mapper.Map<List<RoleDto>>(await _roleService.GetList().ToListAsync()));
        }

        public IActionResult CreatePartialView() => PartialView();
        [HttpPost]
        public async Task<JsonResult> CreatePartialView(RoleDto entityDto)
        {
            if (ModelState.IsValid)
            {

                await _roleService.CreateAsync(_mapper.Map<ApplicationRole>(entityDto));
                return Json(new { Success = true });
            }
            return Json(new { Success = false, Message = string.Join("\n", ModelState.Values.SelectMany(x => x.Errors.SelectMany(y => y.ErrorMessage))) });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, RoleDto entityDto)
        {
            if (ModelState.IsValid)
            {
                var foundUser = await _roleService.GetByIdAsync(id);

                if (foundUser == null) { return NotFound(); }

                foundUser.Name = entityDto.Name;
                foundUser.Description = entityDto.Description;

                await _roleService.UpdateAsync(foundUser);

                return Json(new { Success = true, Message = "" });
            }
            return Json(new { Success = false, Message = string.Join("\n", ModelState.Values.SelectMany(x => x.Errors.SelectMany(y => y.ErrorMessage))) });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var foundUser = await _roleService.GetByIdAsync(id);

                if (foundUser == null) { return NotFound(); }

                await _roleService.DeleteAsync(foundUser);

                return Json(new { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new { Success = false, ex.Message });
            }

        }
    }
}

RadarService.WebApp/Controllers/RoleActionsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RadarService.Authorization.Dtos;
using RadarService.Authorization.Helpers;
using RadarService.Authorization.Services;
using RadarService.WebApp.Dtos;

namespace RadarService.WebApp.Controllers
{
    public class RoleActionsController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;
        private readonly IMvcControllerDiscovery _mvcControllerDiscovery;

        public RoleActionsController(IRoleService roleService, IMapper mapper, IMvcControllerDiscovery mvcControllerDiscovery)
        {
            _roleService = roleService;
            _mapper = mapper;
            _mvcControllerDiscovery = mvcControllerDiscovery;
        }

        public async Task<IActionResult> Index(string id)
        {
            var foundRole = await _roleService.GetByIdAsync(id);

            ViewBag.Role = _mapper.Map<RoleDto>(foundRole);

            ViewData["SelectedControllers"] = string.IsNullOrEmpty(foundRole.Access) ? new List<MvcControllerInfo>() : JsonConvert.DeserializeObject<List<MvcControllerInfo>>(foundRole.Access);

            return View();
        }

        public IActionResult GetControllers()
        {
            return Json(_mvcControllerDiscovery.GetControllerInfos());
        }
        [HttpPost]
        public async Task<IActionResult> AssignActionToRole(string id, IEnumerable<string> selectedControllers)
        {

            if (id != null)
            {
                var foundRole = await _roleService.GetByIdAsync(id);

                var allControllerInfos = _mvcControllerDiscovery.GetControllerInfos();

                var foundSelectedControllers = allControllerInfos.Where(x => selectedControllers.Contains(x.Id)).ToList();

                var accessJson = JsonConvert.SerializeObject(foundSelectedControllers);

                if (foundRole.Access == accessJson) return Ok("Role Actions Updated Successfully(NoChange)");

                foundRole.Access = accessJson;

                await _roleService.UpdateAsync(foundRole);

               return Ok("Role Actions Updated Successfully...");
            }

            return NotFound();
        }
    }
}

RadarService.WebApp/Controllers/RoleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RadarService.Authorization.Dtos;
using RadarService.Authorization.Models;
using RadarService.Authorization.Services;
using RadarService.WebApp.Dtos;

namespace RadarService.WebApp.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;

        public RoleController(IRoleService roleService, IMapper mapper)
        {

            _roleService = roleService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetList()
        {
            return Json(_mapper.Map<List<RoleDto>>(await _roleService.GetList().ToListAsync()));
        }

        public IActionResult CreatePartialView() => PartialView();
        [HttpPost]
        public async Task<JsonResult> CreatePartialView(RoleDto entityDto)
        {
            if (ModelState.IsValid)
            {

                await _roleService.CreateAsync(_mapper.Map<ApplicationRole>(entityDto));
                return Json(new { Success = true });
            }
            return Json(new { Success = false, Message = string.Join("\n", ModelState.Values.SelectMany(x => x.Errors.SelectMany(y => y.ErrorMessage))) });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, RoleDto entityDto)
        {
            if (ModelState.IsValid)
            {
                var foundUser = await _roleService.GetByIdAsync(id);

                if (foundUser == null) { return NotFound(); }

                foundUser.Name = entityDto.Name;
                foundUser.Description = entityDto.Description;

                await _roleService.UpdateAsync(foundUser);

                return Json(new { Success = true, Message = "" });
            }
            return Json(new { Success = false, Message = string.Join("\n", ModelState.Values.SelectMany(x => x.Errors.SelectMany(y => y.ErrorMessage))) });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var foundUser = await _roleService.GetByIdAsync(id);

                if (foundUser == null) { return NotFound(); }

                await _roleService.DeleteAsync(foundUser);

                return Json(new { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new { Success = false, ex.Message });
            }

        }
    }
}

RadarService.WebApp/Controllers/RoleUsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RadarService.Authorization.Models;
using RadarService.Authorization.Services;
using RadarService.WebApp.Dtos;

namespace RadarService.WebApp.Controllers
{
    public class RoleUsersController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        private readonly IUserRoleService _userRoleService;
        private readonly IMapper _mapper;

        public RoleUsersController(IMapper mapper, IUserService userService, IRoleService roleService, IUserRoleService userRoleService)
        {
            _mapper = mapper;
            _userService = userService;
            _roleService = roleService;
            _userRoleService = userRoleService;
        }

        public async Task<IActionResult> Index(string id)
        {
            ViewBag.Role = _mapper.Map<RoleDto>(await _roleService.GetByIdAsync(id));


            return View();
        }

        public async Task<IActionResult> GetList(string roleId)
        {
            return Json(_mapper.Map<List<UserRoleDto>>(await _userRoleService.GetList().Where(x=>x.RoleId == roleId).ToListAsync()));
        }

        public async Task<IActionResult> GetUserList()
        {
            var list = await _userService.GetAll().Select(x => new SelectListItem() { Text = $"{x.FirstName} {x.LastName} ({x.EmployeeNumber})", Value = x.Id }).ToListAsync();

            return Json(list);
        }

        public async Task<IActionResult> GetRoleList()
        {
            var list = await _roleService.GetList().Select(x => new SelectListItem() { Text = x.Name, Value = x.Id }).ToListAsync();

            return Json(list);
        }

        public async Task<IActionResult> CreatePartialView(string id)
        {
            var existingUsers = await _userRoleService.GetList().Where(x=>x.RoleId == id).Select(x=>x.UserId).ToListAsync();
            ViewData["UserId"] = new SelectList(_userService.GetAll().Where(x=>!existingUsers.Contains(x.Id)).Select(x=>new { x.Id,Name=$"{x.FirstName} {x.LastName} ({x.EmployeeNumber})" }), "Id", "Name");
            ViewData["RoleId"] = new SelectList(_roleService.GetList(),"Id","Name");
            return PartialView(new UserRoleDto(){RoleId = id});
        }
        [HttpPost]
        public async Task<JsonResult> CreatePartialView(UserRoleDto entityDto)
        {
            if (ModelState.IsValid)
            {
            
                await _userRoleService.CreateAsync(new Microsoft.AspNetCore.Identity.IdentityUserRole<string>()
                {
                    UserId = entityDto.UserId,
                    RoleId = entityDto.RoleId,
                });
                return Json(new { Success = true });
            }
            return Json(new { Success = false, Message = string.Join("\n", ModelState.Values.SelectMany(x => x.Errors.SelectMany(y => y.ErrorMessage))) });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, string roleId, UserRoleDto entityDto)
        {
            if (ModelState.IsValid)
            {
                var foundUserRole = await _userRoleService.GetByIdAsync(userId);

                if (foundUserRole == null) { return NotFound(); }


                foundUserRole.UserId = entityDto.UserId;
                foundUserRole.RoleId = entityDto.RoleId;

                await _userRoleService.UpdateAsync(foundUserRole);

                return Json(new { Success = true, Message = "" });
            }
            return Json(new { Success = false, Message = string.Join("\n", ModelState.Values.SelectMany(x => x.Errors.SelectMany(y => y.ErrorMessage))) });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string userId, string roleId)
        {
            try
            {
                var foundUser = await _userRoleService.GetByIdAsync(userId, roleId);

                if (foundUser == null) { return NotFound(); }

                await _userRoleService.DeleteAsync(foundUser);

                return Json(new { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new { Success = false, ex.Message });
            }

        }
    }
}

RadarService.WebApp/Views/Role/CreatePartialView.cshtml
@model RadarService.WebApp.Dtos.RoleDto
<h1>Create</h1>

<h4>Device</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="CreatePartialView" data-ajax="true" data-ajax-mode="replace" data-ajax-success="CreateOnSuccess" data-ajax-update="#modalBody">
           @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

RadarService.WebApp/Views/Role/Index.cshtml
@using RadarService.WebApp.Dtos;
@{
    ViewData["Title"] = "Index";

    var role = (RoleDto)ViewBag.Role;
}

<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title">Role List</h3>
        <div class="card-toolbar">
        </div>
    </div>
    <div class="card-body">
        <div id="jqxgrid"></div>
    </div>

</div>



<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body" id="modalBody">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<script>






    $(document).ready(function () {
        var source =
        {
            datatype: "json",
            datafields: [
                { name: 'Id', type: 'string' },
                { name: 'Name', type: 'string' },
                { name: 'Description', type: 'string' },


            ],
            id: 'Id',
            url: '@Url.Action("GetList")',
            updaterow: function (rowid, newdata, commit) {
                $.post('@Url.Action("Edit")', { id: rowid, entityDto: newdata }, function (data) {
                    if (data.Success) {
                        commit(true);
                    } else {
                        commit(false);
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: data.Message,

                        });
                    }

                });


            },
            deleterow: function (rowid, commit) {
                var rowdata = $('#jqxgrid').jqxGrid('getrowdatabyid', rowid);
                Swal.fire({
                    title: 'Do you want to delete this item?',
                    showCancelButton: true,
                    confirmButtonText: 'Delete',
                }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if (result.isConfirmed) {
                        $.post('@Url.Action("DeleteConfirmed")', { id: rowdata.Id }, function (data) {
                            if (data.Success) {
                                commit(true);
                            } else {
                                commit(false);
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Oops...',
                                    text: data.Message,

                                });
                            }

                        });
                    } else {
                        commit(false);
                    }
                })

            }
        };
        var dataAdapter = new $.jqx.dataAdapter(source);
        $("#jqxgrid").jqxGrid(
            {
                theme: 'bootstrap',
                altrows: true,
                columnsresize: true,
                width: '%100',
                source: dataAdapter,
                sortable: true,
                filterable: true,
                filtermode: "excel",
                autoshowfiltericon: true,
                enabletooltips: true,
                pageable: true,
                autoheight: true,
                pagesize: 20,
                pagerButtonsCount: 10,
                showaggregates: true,
                showfilterrow: true,
                selectionmode: 'singlecell',
                showfilterrow: true,
                editable: true,
                showtoolbar: true,
                rendertoolbar: function (toolbar) {
                    var me = this;
                    var container = $("<div style='margin: 5px; height:160px !important;'></div>");
                    toolbar.append(container);
                    container.append('<input id="addNewButton" type="button" value="Add New" />');
                    $("#addNewButton").jqxButton({ template: "primary" });


                    $("#cloneTagButton")
                        .on('click',
                            function () {
                                $.get('@Url.Action("CloneModal", "TerminalTags")',
                                    function (responseData) {
                                        $("#cloneTagModal").modal();
                                        $("#cloneTagModalBody").html(responseData);
                                    });
                            });
                    $("#addNewButton")
                        .on('click',
                            function () {

                                $.get("@Url.Action("CreatePartialView")",
                                    function (data) {
                                        $('.modal-body').html(data);
                                        jQuery.validator.unobtrusive.parse('.modal-body')
                                        $("#myModal").modal("show");
                                    });
                            });
                },
                columns: [
                    { text: 'Name', datafield: 'Name' },
                    { text: 'Description', datafield: 'Description' },
                    {
                        text: 'Assigned Users', datafield: 'AssignedUsers', columntype: 'button', cellsrenderer: function () {
                            return "AssignedUsers";
                        }, buttonclick: function (row) {

                            var rowid = $('#jqxgrid').jqxGrid('getrowid', row);
                            var rowdata = $("#jqxgrid").jqxGrid('getrowdatabyid', rowid);


                            window.open('@Url.Action("Index","RoleUsers")?Id=' + rowdata.Id, '_blank')
                        }
                    },
                    {
                        text: 'Assign Actions', datafield: 'AssignedActions', columntype: 'button', cellsrenderer: function () {
                            return "AssignedActions";
                        }, buttonclick: function (row) {

                            var rowid = $('#jqxgrid').jqxGrid('getrowid', row);
                            var rowdata = $("#jqxgrid").jqxGrid('getrowdatabyid', rowid);


                            window.open('@Url.Action("Index","RoleActions")?Id=' + rowdata.Id, '_blank')
                        }
                    },
                    {
                        text: 'Delete', datafield: 'Delete', columntype: 'button', cellsrenderer: function () {
                            return "Delete";
                        }, buttonclick: function (row) {

                            var rowid = $('#jqxgrid').jqxGrid('getrowid', row);
                            var commit = $("#jqxgrid").jqxGrid('deleterow', rowid);



                        }
                    }
                ]
            });
    });
    var CreateOnSuccess = function (data) {
        if (data.Success) {
            $("#myModal").modal("hide");
            $("#jqxgrid").jqxGrid('updatebounddata', 'cells');
        } else {
            $("#myModal").modal("hide");
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: data.Message,

            });
        }
    };

</script>